export default class Url {
  static mall = '/home/CommodityPhoneList'
  static product = '/home/CommodityPhoneDetail'
  static buy = '/order/add'
  static orderList = '/order/OrderList'
  static orderSubmit = '/order/Submit'
  static orderDetail = '/order/OrderDetail'
  static ModifyResiver = '/order/ModifyResiver'
  static GetPostAddress = '/Customer/GetPostAddress'
  static AddPostAddress = '/Customer/AddPostAddress'
  static ModifyPostAddress = '/Customer/ModifyPostAddress'
  static SetDefaultAddress = '/Customer/SetDefaultAddress'
  static DeletePostAddress = '/Customer/DeletePostAddress'
  static OrderCancel = '/order/Cancel'
}
