export default class Url {
  static mall = '/home/CommodityPhoneList'
  static product = '/home/CommodityPhoneDetail'
  static buy = '/order/add'
  static orderList = '/order/OrderList'
  static orderSubmit = '/order/Submit'
  static orderDetail = '/order/OrderDetail'
  static ModifyResiver = '/order/ModifyResiver'
  static GetPostAddress = '/Customer/GetPostAddress'
  static AddPostAddress = '/Customer/AddPostAddress'
  static ModifyPostAddress = '/Customer/ModifyPostAddress'
  static SetDefaultAddress = '/Customer/SetDefaultAddress'
  static DeletePostAddress = '/Customer/DeletePostAddress'
  static Cancel = '/order/Cancel'
  static Receipt = '/Order/Receipt'
  static PayOrderBill = '/Order/PayOrderBill'
  static LoginCustomer = '/Customer/LoginCustomer'
  static RegistCustomer = '/Customer/RegistCustomer'
  static ModifyCustomerPwd = '/Customer/ModifyCustomerPwd'
  static SendSMS = '/Customer/SendSMS'
  static LogisticsDetail = '/Order/Trace'
}
